apiVersion: v1
kind: Namespace
metadata:
  name: doppler-secrets-sync
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: doppler-secrets-sync-service-account
  namespace: doppler-secrets-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: doppler-secrets-sync-cluster-role
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: doppler-secrets-sync-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: doppler-secrets-sync-cluster-role
subjects:
- kind: ServiceAccount
  name: doppler-secrets-sync-service-account
  namespace: doppler-secrets-sync
